import type { Locale } from './nav'
import { DEFAULT_LOCALE } from './nav'

/** Every string the chrome says, per language. The pages are MDX; this is not. */
const STRINGS = {
  en: {
    skipToContent: 'Skip to content',
    primaryNav: 'Primary',
    docsNav: 'Documentation',
    openNav: 'Open navigation',
    closeNav: 'Close navigation',
    headerUse: 'Use it',
    headerDocs: 'Docs',
    headerReference: 'Reference',
    headerApi: 'Python API',
    onThisPage: 'On this page',
    breadcrumbRoot: 'Docs',
    pagerLabel: 'Previous and next page',
    previous: '← Previous',
    next: 'Next →',
    searchPlaceholderShort: 'Search the docs',
    searchPlaceholder: 'Search pages, concepts, statements…',
    searchLabel: 'Search the documentation',
    searchEmptyPrefix: 'Nothing matches',
    searchHint: 'Type to search. Try',
    searchNavigate: 'to navigate',
    searchOpen: 'to open',
    searchClose: 'to close',
    language: 'Language',
    thisSite: 'this site',
    readme: 'README',
    themeToLight: 'Switch to light theme',
    themeToDark: 'Switch to dark theme',
    notFoundTitle: 'Page not found',
    notFoundBody: 'Nothing is documented at',
    notFoundBack: 'Back to the documentation index',
    footerDocs: 'Documentation',
    footerIssues: 'Issues',
    footerContributing: 'Contributing',
    footerAlsoIn: 'The README, also in',
    footerLicence: 'licence',
    copy: 'Copy',
    copied: 'Copied',
    copyCode: 'Copy code',
    calloutNote: 'Note',
    calloutProved: 'Proved',
    calloutLimit: 'Limit',
    calloutDanger: 'Careful',
  },
  'pt-BR': {
    skipToContent: 'Pular para o conteúdo',
    primaryNav: 'Principal',
    docsNav: 'Documentação',
    openNav: 'Abrir navegação',
    closeNav: 'Fechar navegação',
    headerUse: 'Usar',
    headerDocs: 'Docs',
    headerReference: 'Referência',
    headerApi: 'API Python',
    onThisPage: 'Nesta página',
    breadcrumbRoot: 'Docs',
    pagerLabel: 'Página anterior e próxima',
    previous: '← Anterior',
    next: 'Próxima →',
    searchPlaceholderShort: 'Buscar na documentação',
    searchPlaceholder: 'Busque páginas, conceitos, comandos…',
    searchLabel: 'Buscar na documentação',
    searchEmptyPrefix: 'Nada corresponde a',
    searchHint: 'Digite para buscar. Tente',
    searchNavigate: 'para navegar',
    searchOpen: 'para abrir',
    searchClose: 'para fechar',
    language: 'Idioma',
    thisSite: 'este site',
    readme: 'README',
    themeToLight: 'Mudar para o tema claro',
    themeToDark: 'Mudar para o tema escuro',
    notFoundTitle: 'Página não encontrada',
    notFoundBody: 'Não há nada documentado em',
    notFoundBack: 'Voltar ao índice da documentação',
    footerDocs: 'Documentação',
    footerIssues: 'Issues',
    footerContributing: 'Contribuir',
    footerAlsoIn: 'O README, também em',
    footerLicence: 'licença',
    copy: 'Copiar',
    copied: 'Copiado',
    copyCode: 'Copiar código',
    calloutNote: 'Nota',
    calloutProved: 'Provado',
    calloutLimit: 'Limite',
    calloutDanger: 'Atenção',
  },
} as const

export type Strings = (typeof STRINGS)['en']

export function strings(locale: Locale): Strings {
  return (STRINGS[locale] ?? STRINGS[DEFAULT_LOCALE]) as Strings
}
