import type { Locale } from './nav'
import { DEFAULT_LOCALE } from './nav'

/** Every string the chrome says, per language. The pages are MDX; this is not. */
const STRINGS = {
  en: {
    skipToContent: 'Skip to content',
    primaryNav: 'Primary',
    docsNav: 'Documentation',
    openNav: 'Open navigation',
    closeNav: 'Close navigation',
    headerUse: 'Use it',
    headerDocs: 'Docs',
    headerReference: 'Reference',
    headerApi: 'Python API',
    onThisPage: 'On this page',
    breadcrumbRoot: 'Docs',
    pagerLabel: 'Previous and next page',
    previous: '← Previous',
    next: 'Next →',
    searchPlaceholderShort: 'Search the docs',
    searchPlaceholder: 'Search pages, concepts, statements…',
    searchLabel: 'Search the documentation',
    searchEmptyPrefix: 'Nothing matches',
    searchHint: 'Type to search. Try',
    searchNavigate: 'to navigate',
    searchOpen: 'to open',
    searchClose: 'to close',
    language: 'Language',
    thisSite: 'this site',
    readme: 'README',
    themeToLight: 'Switch to light theme',
    themeToDark: 'Switch to dark theme',
    notFoundTitle: 'Page not found',
    notFoundBody: 'Nothing is documented at',
    notFoundBack: 'Back to the documentation index',
    footerDocs: 'Documentation',
    footerIssues: 'Issues',
    footerContributing: 'Contributing',
    footerAlsoIn: 'The README, also in',
    footerLicence: 'licence',
    copy: 'Copy',
    copied: 'Copied',
    copyCode: 'Copy code',
    calloutNote: 'Note',
    calloutProved: 'Proved',
    calloutLimit: 'Limit',
    calloutDanger: 'Careful',
    copyMarkdown: 'Copy as Markdown',
    copiedMarkdown: 'Copied',
    viewMarkdown: 'View as Markdown',
    forAgents: 'For agents',
  },
  'pt-BR': {
    skipToContent: 'Pular para o conteúdo',
    primaryNav: 'Principal',
    docsNav: 'Documentação',
    openNav: 'Abrir navegação',
    closeNav: 'Fechar navegação',
    headerUse: 'Usar',
    headerDocs: 'Docs',
    headerReference: 'Referência',
    headerApi: 'API Python',
    onThisPage: 'Nesta página',
    breadcrumbRoot: 'Docs',
    pagerLabel: 'Página anterior e próxima',
    previous: '← Anterior',
    next: 'Próxima →',
    searchPlaceholderShort: 'Buscar na documentação',
    searchPlaceholder: 'Busque páginas, conceitos, comandos…',
    searchLabel: 'Buscar na documentação',
    searchEmptyPrefix: 'Nada corresponde a',
    searchHint: 'Digite para buscar. Tente',
    searchNavigate: 'para navegar',
    searchOpen: 'para abrir',
    searchClose: 'para fechar',
    language: 'Idioma',
    thisSite: 'este site',
    readme: 'README',
    themeToLight: 'Mudar para o tema claro',
    themeToDark: 'Mudar para o tema escuro',
    notFoundTitle: 'Página não encontrada',
    notFoundBody: 'Não há nada documentado em',
    notFoundBack: 'Voltar ao índice da documentação',
    footerDocs: 'Documentação',
    footerIssues: 'Issues',
    footerContributing: 'Contribuir',
    footerAlsoIn: 'O README, também em',
    footerLicence: 'licença',
    copy: 'Copiar',
    copied: 'Copiado',
    copyCode: 'Copiar código',
    calloutNote: 'Nota',
    calloutProved: 'Provado',
    calloutLimit: 'Limite',
    calloutDanger: 'Atenção',
    copyMarkdown: 'Copiar como Markdown',
    copiedMarkdown: 'Copiado',
    viewMarkdown: 'Ver como Markdown',
    forAgents: 'Para agentes',
  },
  'zh-CN': {
    skipToContent: '跳到正文',
    primaryNav: '主导航',
    docsNav: '文档',
    openNav: '打开导航',
    closeNav: '关闭导航',
    headerUse: '使用',
    headerDocs: '文档',
    headerReference: '参考',
    headerApi: 'Python API',
    onThisPage: '本页内容',
    breadcrumbRoot: '文档',
    pagerLabel: '上一页与下一页',
    previous: '← 上一页',
    next: '下一页 →',
    searchPlaceholderShort: '搜索文档',
    searchPlaceholder: '搜索页面、概念、语句…',
    searchLabel: '搜索文档',
    searchEmptyPrefix: '没有匹配',
    searchHint: '输入以搜索。试试',
    searchNavigate: '导航',
    searchOpen: '打开',
    searchClose: '关闭',
    language: '语言',
    thisSite: '本站',
    readme: 'README',
    themeToLight: '切换到浅色主题',
    themeToDark: '切换到深色主题',
    notFoundTitle: '页面不存在',
    notFoundBody: '这个位置没有任何文档：',
    notFoundBack: '返回文档索引',
    footerDocs: '文档',
    footerIssues: 'Issues',
    footerContributing: '参与贡献',
    footerAlsoIn: 'README 也有这些语言',
    footerLicence: '许可证',
    copy: '复制',
    copied: '已复制',
    copyCode: '复制代码',
    calloutNote: '说明',
    calloutProved: '已证明',
    calloutLimit: '局限',
    calloutDanger: '注意',
    copyMarkdown: '复制为 Markdown',
    copiedMarkdown: '已复制',
    viewMarkdown: '查看 Markdown',
    forAgents: '给智能体',
  },
} as const

export type Strings = (typeof STRINGS)['en']

export function strings(locale: Locale): Strings {
  return (STRINGS[locale] ?? STRINGS[DEFAULT_LOCALE]) as Strings
}
